POST  http://localhost:3003/api/blogs/
Content-Type: application/json

{
    "title": "GET and POST are the most important methods of HTTP protocol",
    "author": "A3",
    "url": "http://www.google.com"
}

###

GET  http://localhost:3003/api/blogs/